.changeset/silly-pigs-wonder.md
packages/hardhat-forge/src/forge/artifacts.ts

When turning a JS object into a JSON string, the order
of the keys will dictate the order of the keys in
the JSON. This change matches the format that hardhat
uses when writing the JSON artifacts to disk.
The format used by hardhat is shown below.
```
[
"_format",
"abi",
"bytecode",
"contractName",
"deployedBytecode",
"deployedLinkReferences",
"linkReferences",
"sourceName"
]
```

feat(hardhat-forge): update key ordering of hh artifact

---

.changeset/strong-cheetahs-call.md
packages/hardhat-forge/src/forge/artifacts.ts
packages/hardhat-forge/src/index.ts
packages/hardhat-forge/test/fixture-projects/hardhat-project/src/foo/Contract2.sol
packages/hardhat-forge/test/helpers.ts
packages/hardhat-forge/test/project.test.ts

This will now write hardhat style artifacts to disk after running `hardhat compile`.
An example of how hardhat does this:
```
artifacts/
├── build-info
├── contracts
│   ├── chugsplash
│   ├── L1
│   ├── L2
│   ├── libraries
│   ├── standards
└── @openzeppelin
├── contracts
└── contracts-upgradeable
```
The layout of the artifacts mirrors the layout of the contract source, unlike `foundry` which flattens all of the artifacts into a single top level directory
As of this PR, `artifacts/build-info` is not populated. I do not believe deps are compiled either unless they are used (the openzeppelin contracts in this example), hh seems to always compile them.
I do think that having the functionality to build hardhat style artifacts would be more suited for `ethers-rs` as the relative path to the …

feat: write hardhat style artifacts to disk

---

.changeset/neat-planes-peel.md
package.json

Since `packages/hardhat` depends on `packages/hardhat-anvil`
and `packages/hardhat-forge`, they must be built first.
If they are not, building `packages/hardhat` will fail
being unable to locate the other packages.
See https://github.com/foundry-rs/hardhat/runs/6651154556?check_suite_focus=true
```
Error: packages/hardhat/src/index.ts(1,24): error TS2307: Cannot find module '@foundry-rs/hardhat-forge' or its corresponding type declarations.
Error: packages/hardhat/src/index.ts(2,24): error TS2307: Cannot find module '@foundry-rs/hardhat-anvil' or its corresponding type declarations.
```

fix: ts build ordering

---

.changeset/fuzzy-cougars-drive.md
packages/hardhat-forge/src/forge/artifacts.ts
packages/hardhat-forge/src/forge/build/index.ts
packages/hardhat-forge/src/index.ts

Call `runSuper` after compiling so that other plugins that hook into the `compile` task are still called.
I discovered that `hardhat/typechain` was not being ran with this plugin and I believe that this is the solution.
Need to test locally to be sure. Note that calling `runSuper` here does not invoke the hardhat compiler
toolchain. Two additional functions are added that I believe should be part of the `IArtifacts` interface but are not.
Both of them are noops here, attempting to implement them would require a much larger change. Without them,
there is a `function is not defined` error.
Also delete some dead code in the constructor of `ForgeArtifacts`

feat: allow other plugins to be composed with `build`

---

.changeset/many-rivers-jump.md
packages/hardhat-forge/src/forge/artifacts.ts

Typechain uses a private method on the artifact
with an unsafe `any` typecast to get artifact paths.
To work with typechain, this method must exist until
typechain is updated.
The issue is here: https://github.com/dethcrypto/TypeChain/issues/544
hardhat implementation: https://github.com/NomicFoundation/hardhat/blob/783650c5711f457ad63cc7eee9ac190d0ff264fc/packages/hardhat-core/src/internal/artifacts.ts#L379

fix(hh/forge): typechain support

---

.changeset/tame-otters-sing.md
packages/hardhat-forge/src/forge/artifacts.ts
packages/hardhat-forge/test/fixture-projects/hardhat-project/foundry.toml
packages/hardhat-forge/test/fixture-projects/hardhat-project/src/Contract.sol
packages/hardhat-forge/test/project.test.ts

Implement a naive `getBuildInfo` function. This is useful
for tooling that integrates more deeply with the hardhat ecosystem.
Note that this implementation is not 100% with the output
that the hardhat compiler toolchain outputs, but the output
is good enough to get more tooling to be compatible.

feat: `Artifacts.getBuildInfo`

---

.changeset/nine-ads-melt.md
packages/hardhat-forge/src/forge/artifacts.ts
packages/hardhat-forge/test/project.test.ts

The relative path to the file from the root
of the project should be used as the source name
in the artifact.
Closes https://github.com/foundry-rs/hardhat/issues/36
This will fix tooling that depends on the source name:
https://github.com/defi-wonderland/smock/blob/27fe7a5f3c351714257cdc98204e282932c11e12/src/utils/storage.ts#L54

hardhat-forge: use the correct source name

---

.changeset/strange-rice-decide.md
packages/hardhat-anvil/test/helpers.ts
packages/hardhat-anvil/test/index.ts
packages/hardhat/test/helpers.ts
packages/hardhat/test/project.test.ts

Closes #39 #53
fetch a free port and explicitly set the `port` value when launching anvil

test: explicitly set port for anvil

---

.changeset/poor-zebras-allow.md
packages/hardhat-forge/src/forge/artifacts.ts
packages/hardhat-forge/src/forge/build/build.ts
packages/hardhat-forge/src/forge/config/config.ts
packages/hardhat-forge/src/forge/types.ts
packages/hardhat-forge/src/index.ts
packages/hardhat-forge/test/fixture-projects/hardhat-project/foundry.toml
packages/hardhat-forge/test/project.test.ts

This PR is a companion to https://github.com/foundry-rs/foundry/pull/2012
It adds better support for `hre.artifacts.getBuildInfo`. The hardhat plugin doesn't currently have access to the values that make up the hash for the filename, so it simply searches through each `BuildInfo` to find the correct one. Not super ideal, but works for now.
It will generate the debug files in the same way that hardhat does, so hardhat plugins that rely on the debug files should just work.
To be able to optimize this, the hardhat plugin needs to be able to compute `md5(_format,solcVersion,solcLongVersion,input)`

feat: better `BuildInfo` support

---

.changeset/breezy-walls-greet.md
packages/hardhat-forge/src/forge/build/index.ts
packages/hardhat-forge/src/forge/types.ts
packages/hardhat-forge/src/index.ts
packages/hardhat-forge/test/fixture-projects/hardhat-project/hardhat.config.ts
packages/hardhat-forge/test/project.test.ts

The `hardhat.config.ts` now can have a `foundry` section that
allows users to place config values in. This makes it so that
expensive operations like generating the build info can be placed
in the `hardhat.config.ts` and not in the `foundry.toml` so that
`forge build` can be ligher than `hardhat compile`.

feat(hardhat-forge): add `foundry` config section

---

.changeset/sweet-wasps-share.md
packages/hardhat-forge/src/index.ts

Was experiencing hardhat oom'ing, the hh docs
recommend using `lazyObject` when building plugins
that modify the `hre` of the `HardhatConfig` objects.

fix: make foundry config a lazy object

---

.changeset/popular-humans-greet.md
packages/hardhat-forge/src/forge/build/index.ts
packages/hardhat-forge/src/forge/types.ts
packages/hardhat-forge/src/index.ts

Allow the user to configure `runSuper` in the
build task. Allowing the user to run this will
allow for more composability with other hardhat
based tooling but will slow down the build.
It was previously defaulted to true, but I found
in practice that its generally not necessary to
be true for just compilation. Things like `typechain`
will not automatically run afterwards, but `typechain`
doesn't currently work exactly the same as the foundry
`Artifacts` doesn't have the concept of `validArtifacts`
populated after building. We run `typechain` on its own
after compilation to get around this difference, so
always calling `runSuper` just slows down the build.

feat: configurable runSuper

---

.changeset/popular-humans-greet.md
packages/hardhat-forge/src/forge/build/index.ts
packages/hardhat-forge/src/forge/types.ts
packages/hardhat-forge/src/index.ts

Starts the release process by merging develop into master. After merge, we should base the changesets PR that gets opened automatically on develop then merge and merge develop into master again to finally trigger the release
---
Allow the user to configure `runSuper` in the
build task. Allowing the user to run this will
allow for more composability with other hardhat
based tooling but will slow down the build.
It was previously defaulted to true, but I found
in practice that its generally not necessary to
be true for just compilation. Things like `typechain`
will not automatically run afterwards, but `typechain`
doesn't currently work exactly the same as the foundry
`Artifacts` doesn't have the concept of `validArtifacts`
populated after building. We run `typechain` on its own
after …

feat: configurable runSuper (#73)

---

.changeset/seven-bees-itch.md
packages/hardhat-forge/package.json
packages/hardhat-forge/src/forge/build/index.ts
packages/hardhat-forge/src/forge/types.ts
packages/hardhat-forge/src/index.ts
packages/hardhat-forge/test/fixture-projects/hardhat-project/hardhat.config.ts

Add an additional config option to the hardhat config
that allows a user to disable writing the hardhat artifacts.
It defaults to true.
The config option looks like:
```js
const config: HardhatUserConfig = {
foundry: {
writeArtifacts: true,
},
}
```
This PR ensures that the artifacts are actually written to disk, because wrapping the `hre.Artifacts` in a `lazyObject` means that that the code will not execute unless `hre.Artifacts` is referenced someplace in the codebase. This means that if something doesn't touch `hre.Artifacts`, they will not be written to disk. This moves the logic of writing to disk outside of the creation of `hre.Artifacts` and puts it behind a config flag so that users can disable the functionality if they desire.

hardhat-forge: configurable artifact output

---

.changeset/seven-bees-itch.md
packages/hardhat-forge/package.json
packages/hardhat-forge/src/forge/build/index.ts
packages/hardhat-forge/src/forge/types.ts
packages/hardhat-forge/src/index.ts
packages/hardhat-forge/test/fixture-projects/hardhat-project/hardhat.config.ts

Begin the release process by merging develop into master
----
Add an additional config option to the hardhat config
that allows a user to disable writing the hardhat artifacts.
It defaults to true.
The config option looks like:
```js
const config: HardhatUserConfig = {
foundry: {
writeArtifacts: true,
},
}
```

hardhat-forge: configurable artifact output (#80)

---

.changeset/late-rivers-applaud.md
packages/hardhat-forge/src/forge/build/build.ts
packages/hardhat-forge/src/forge/config/config.ts
packages/hardhat-forge/src/index.ts
packages/hardhat-forge/test/fixture-projects/hardhat-project/foundry.toml

Allow the `build_info_path` config option to be parsed
and passed through the hardhat plugin. It will correctly
create the debug files that point to the build info files
dynamically based on the configured build info path.
The tests that fetch the build info objects still pass, they
look up the path from the debug file to the build info file.

feat(hardhat-forge): build info path config

---

.changeset/late-rivers-applaud.md
packages/hardhat-forge/src/forge/build/build.ts
packages/hardhat-forge/src/forge/config/config.ts
packages/hardhat-forge/src/index.ts
packages/hardhat-forge/test/fixture-projects/hardhat-project/foundry.toml

Merging develop into master to start the release process
---
Allow the `build_info_path` config option to be parsed
and passed through the hardhat plugin. It will correctly
create the debug files that point to the build info files
dynamically based on the configured build info path.
The tests that fetch the build info objects still pass, they
look up the path from the debug file to the build info file.

feat(hardhat-forge): build info path config (#84)

---

.changeset/lazy-news-hide.md
packages/hardhat-forge/src/forge/artifacts.ts
packages/hardhat-forge/test/project.test.ts

The build info compiler output metadata is serialized as a string and hardhat tooling that reads these files expects the string to be an object. This PR looks to see if the metadata is a string and then parses the json string into an object.
The first commit includes a failing test to show that this is a problem.
Perhaps another way to fix this would be to serialize the metadata as a json object in ethers-solc.

hardhat-forge: parse string metadata

---

.changeset/late-rivers-applaud.md
.changeset/lazy-news-hide.md
packages/hardhat-forge/CHANGELOG.md
packages/hardhat-forge/package.json
packages/hardhat-forge/src/forge/artifacts.ts
packages/hardhat-forge/src/forge/build/build.ts
packages/hardhat-forge/src/forge/config/config.ts
packages/hardhat-forge/src/index.ts
packages/hardhat-forge/test/fixture-projects/hardhat-project/foundry.toml
packages/hardhat-forge/test/project.test.ts

Rebases develop on master so that the 2 branches do not diverge. Will follow up with a release PR after this one
Fixes https://github.com/foundry-rs/hardhat/pull/87 being merged directly into master instead of first being merged into develop and then develop being merged into master

fix: rebase develop on master

---

.changeset/real-beds-enjoy.md
packages/hardhat-forge/.gitignore
packages/hardhat-forge/src/forge/artifacts.ts
packages/hardhat-forge/test/fixture-projects/hardhat-project/foundry.toml
packages/hardhat-forge/test/fixture-projects/hardhat-project/src/foo/Contract2.sol
packages/hardhat-forge/test/project.test.ts

Properly handle building artifacts when multiple contracts
have the same name. Previously this would fail as fully qualified
names were not being used and it would become ambiguous which
contract was being referenced. Now paths are converted into
fully qualified names such that it is no longer ambiguous what
contract is being referenced.

hardhat-forge: multiple contracts same name

---

.changeset/cold-ways-refuse.md
packages/hardhat-forge/src/forge/artifacts.ts

The artifact paths and filenames are based on the names
of the files containing the smart contracts and the names of
the contracts inside of the files.
The npm package `true-case-path` has a bug that causes it to
ignore directories that are spelled the same but have alternate
casing.
You can see here that it eagerly returns if the case insensitive
regex hits:
https://github.com/Profiscience/true-case-path/blob/8a016e6a8be64c873aba414fbcdb4748e24dc796/index.js#L31
The problem is that it could hit multiple files and we need to check
each, not just the first one that it hits.
The problem is with `DSTest` and `forge-std`, where `DSTest` has
a `test.sol` and `forge-std` has a `Test.sol`. The regex hits
incorrectly and downstream consumers get passed the wrong data.
The fix simply looks to see …

hardhat-forge: handle case insensitive filesystem

---

.changeset/cold-ways-refuse.md
packages/hardhat-forge/src/forge/artifacts.ts

The artifact paths and filenames are based on the names
of the files containing the smart contracts and the names of
the contracts inside of the files.
The npm package `true-case-path` has a bug that causes it to
ignore directories that are spelled the same but have alternate
casing.
You can see here that it eagerly returns if the case insensitive
regex hits:
https://github.com/Profiscience/true-case-path/blob/8a016e6a8be64c873aba414fbcdb4748e24dc796/index.js#L31
The problem is that it could hit multiple files and we need to check
each, not just the first one that it hits.
The problem is with `DSTest` and `forge-std`, where `DSTest` has
a `test.sol` and `forge-std` has a `Test.sol`. The regex hits
incorrectly and downstream consumers get passed the wrong data.
The fix simply looks to see …

hardhat-forge: handle case insensitive filesystem (#97)

---

.changeset/weak-masks-change.md
packages/hardhat-forge/src/forge/artifacts.ts
packages/hardhat-forge/test/project.test.ts

When getting contract artifacts, json files are pulled out of
the artifacts directory. Since metadata files are now emitted by
default as of
https://github.com/foundry-rs/foundry/commit/ad91a4a962ddf2f3c3e340c018482851a5080f01,
extra files were being passed through the hh artifact generation
pipeline which broke things because the hardhat artifacts need
the fully qualified name which is currently pulled from the
ast in the compiler out. It could be possible to brute force
the fully qualified name but that would fail when 2 contracts
have a matching name. This filters out the metadata files
when getting the contract artifacts.
This fixes our broken CI

hardhat-forge: ignore metadata files

---

.changeset/thick-hats-unite.md
packages/hardhat-anvil/src/anvil-server.ts

There is a bug in anvil-server, it's expecting option named `forkurl` but the option is capitalized `forkUrl`

Fix forkUrl option handling
